export { default as FeatureMessage } from './FeatureMessage';
export { default as Testimonials } from './Testimonials';
export { default as MainMessage } from './MainMessage';
export { default as DemoMessage } from './DemoMessage';
export { default as Companies } from './Companies';
export { default as LastMessage } from './LastMessage';
export { default as HowItWorks } from './HowItWorks';
export { default as Footer } from './Footer';
export { default as Help } from './Help/HelpMain';
export { default as HelpResults } from './Help/HelpResults';
export { default as AboutUs } from './AboutUs';
export { default as RobinTeam } from './RobinTeam';
export { default as Benefits } from './Benefits';
export { default as NewsBlog } from './NewsBlog';
export { default as NewsCard} from './NewsBlog/NewsCard';
export { default as Projects } from './Projects';
export { default as Privacy } from './Privacy';
export { default as Terms } from './Terms';